### ISSUE TITLE
Copyright Issues

### ISSUE THREAD

**Issue by Itja** [maheini/FreeStyle-Libre-3-patch#16]
Hey, thanks for gathering information in one place regarding the Libre 3 sensor.

However, I think Abbott will soon come after this repo, because it contains the complete patched app. If I remember correctly, for the Libre 2, only the patch itself survived and the full patched app got shut down everywhere since it contains the original app, which by law nobody but Abbott is allowed for distribution. So everybody had to obtain the unpatched app, the patch, and then patch the app on their own (by executing a single file on their PCs), but it was at least a legal solution. For reference, I think I meant [this repo](https://github.com/TinoKossmann/LibreLink-xDrip-Patch) by Tino Knossmann.

Do you have a way forward when they will come after this?

**Comment by twinko** [comment]
Thats exactly how i remember it too. Crossing fingers it takes some time before they notice. But yes we definitly should ask jkaltes (creator of the patched app) to help us write a patch tutorial for the official app. I imagine something like revanced manager (successor of vanced, same story for youtube patched version) could be a solution. You have a software that does the patching for you.

**Comment by maheini** [comment]
Thank you @Itja 
I'm fully aware of what happened with the libre2 patch and knowing Abbott, I wouldn't be that surprised, as Abbott did already removed a previous (almost finished) solution for the libre 3. However, we keep it going as long as possible. Currently, a lot of people were already able to get their patch - which is already half success.

Here's what's happening, if Abbott really is going to stop the patch distribution:
1. This repo is going to adapt itself. The .apk will be removed of course, but all the instructions etc. will always be available.
2. There are already enough other sources for the patched .apk. In the short term, those will be most relevant, even if we need to download the app from some shady websites.
3. Let me assure you that there will be or will come a similar solution like the libre2 patch. 

This repo may or may not change, but it's definitely not wasted time. We just need to constantly update all informations and we'll be fine to keep going.

**Offtopic**
@twinko Thanks for the mention of revanced manager - I'm a big fan of Vanced and didn't knew the work is still ongoing. A solution like that might be very confortable and maybe even possible, but something like the libre2 patch is already a very simple thing to do (With instructions of course). As you can see from my profile, I am working with the Flutter framework, and to my surprise, revanced manager was made with Flutter. So I might be able to contribute onto a solution like this one day.


I'm going to close this issue for now. If you have any questions or further informations about this topic, feel free to open a new discussion within the [discussions tab](https://github.com/maheini/FreeStyle-Libre-3-patch/discussions).
