### ISSUE TITLE
Takeover don't work (2nd time)

### ISSUE THREAD

**Issue by lmchp** [maheini/FreeStyle-Libre-3-patch#47]
followed the guide - got a AccountID, but when it comes to the takeover by juggluco the error appears?!

![wrong-account](https://user-images.githubusercontent.com/22092740/235506374-3ac64075-dfc4-4735-8d28-0d83acc622b6.jpg)

...which was correct - of course.

**Comment by lmchp** [comment]
...just found an "suspicious UID" in my reports URL of LibreView-Website:
(kind of: https://www.libreview.com/reports/xxxcyyyy-zzzz-aaaa-bbbb-000011112222)
tried the converter with this  (=> conv.java xxxcyyyy-zzzz-aaaa-bbbb-000011112222)
- and got MY(!) "received" AccounID - so not root-access is necessary....

But this ID is wrong as mentioned by the error-msg above....

**Comment by j-kaltes** [comment]
It only works when the sensor was activated when using the same account ID as you have entered in Juggluco. So either the Libre 3 app hadn't a Libreview account associated with it at the moment of activation, or it had a different account ID.

**Comment by maheini** [comment]
Thanks @j-kaltes  for clearing things up. The problem seemes to be resolved.
