### ISSUE TITLE
Buggly 3.3.0 and 3.4.2 is needed !

### ISSUE THREAD

**Issue by henrycoding** [maheini/FreeStyle-Libre-3-patch#53]
There are reports of a fatal bug in the 3.3.0 of the Libre 3 App, and now we need the 3.4.2 version of the app.

But it seems the app has signature verification, could you please help me?

https://www.uclh.nhs.uk/our-services/find-service/children-and-young-peoples-services/children-and-young-peoples-diabetes/diabetes-blog-news-and-updates/urgent-field-safety-notice-freestyle-librelink-and-freestyle-libre-3-android-apps

**Comment by maheini** [comment]
Direct Libre 3 -> Juggluco connection is no more recommended, the development of a patched Libre 3 apk isn't continued anymore. Therefore, I will close this issue. 
You can see all the [recent updates here](https://github.com/maheini/FreeStyle-Libre-3-patch/blob/main/Juggluco-solution/instructions/en/instructions.md)
